### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by rmeister** [arms22/SoftModem#2]
There is no hint about the license, except on the old Google Code [page](https://code.google.com/archive/p/arms22/).

**Comment by arms22** [comment]
Sorry for the late reply .
License is the 'New BSD License'.

**Comment by rmeister** [comment]
No problem.
Added a license file to #1

**Comment by rmeister** [comment]
If you merge you can type 'closes #2' in the comments and it will close this issue automatically.
